name: appv1
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.4.0
  flutter_localizations:
    sdk: flutter
  flutter_redux: "^0.5.0"
  redux: ^3.0.0
  source_gen: any
  rxdart: ^0.18.1
  redux_logging: "^0.3.0"
  http: "^0.11.3+16"
  path_provider : "^0.4.1"
  
  font_awesome_flutter: "^6.0.0"
  built_value: "^5.4.5"
  built_collection: "^3.1.1"
  memoize: "^1.4.0"
  url_launcher: "^3.0.2"
  cached_network_image: any
  share: "^0.5.2"
  fluro: "^1.3.1"
  sliver_fab: "^0.1.0"
  uuid: any
  intl: ^0.15.6
  scoped_model: ^0.2.0
  flutter_sparkline: ^0.0.4
  flutter_circular_chart: ^0.0.3
  bubble_tab_indicator: ^0.1.3
  google_sign_in: ^3.0.5
  firebase_auth:


  
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite : any
  
  #Updated to latest version
  # firebase_core: any Not needed for this implementation. 

 

dev_dependencies:
  flutter_driver:
    sdk: flutter
  #flutter_test:
  #  sdk: flutter
  build_runner: "^0.8.9"
  built_value_generator: "^5.4.5"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/wow.png
    - assets/lit.png
    - assets/weight.png
    - assets/diary.png
    - assets/goals.png
    - assets/heart.png
    - assets/track.png
    - assets/red.png
    - assets/smile.png
    - assets/sad.png
    - assets/activ.png
    - assets/bread.png
    - assets/cal.png
    - assets/plate.png
    - assets/apple.png
    - assets/bol.png
    - assets/fish.png
    - assets/water.png
    - data/food.json
    
    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
